{% set name = "jql" %}
{% set version = "7.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yamafaktory/{{ name }}/archive/refs/tags/{{ name }}-v{{ version }}.tar.gz
  sha256: eb558535914ea28ab39761c0a38f22e46e6a24c2f82d2a930cf003e413c7458d

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/yamafaktory/{{ name }}
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  dev_url: https://github.com/yamafaktory/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
