{% set name = "jql" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yamafaktory/{{ name }}/archive/refs/tags/{{ name }}-v{{ version }}.tar.gz
  sha256: c190bfa3bd3f655a695598d9fd0281116260d1273b1b180d6cfa7b8f35020523

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/yamafaktory/{{ name }}
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  dev_url: https://github.com/yamafaktory/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
