context:
  version: "8.0.9"

package:
  name: jql
  version: ${{ version }}

source:
  url: https://github.com/yamafaktory/jql/archive/refs/tags/jql-v${{ version }}.tar.gz
  sha256: ed754f2d13e396b57b9108b219a8d6ada1d49ec92a076e84cbe6565b2b0a9cdf

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jql --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  homepage: https://github.com/yamafaktory/jql
  repository: https://github.com/yamafaktory/jql

extra:
  recipe-maintainers:
    - danielnachun
