context:
  version: "9.0.0"

package:
  name: jql
  version: ${{ version }}

source:
  url: https://github.com/yamafaktory/jql/archive/refs/tags/jql-v${{ version }}.tar.gz
  sha256: ceaa31419230b51baef3b7084a8510c5fb985220cadcc9e93ed17f2b3b237039

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jql --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  homepage: https://github.com/yamafaktory/jql
  repository: https://github.com/yamafaktory/jql

extra:
  recipe-maintainers:
    - danielnachun
