context:
  version: "8.1.0"

package:
  name: jql
  version: ${{ version }}

source:
  url: https://github.com/yamafaktory/jql/archive/refs/tags/jql-v${{ version }}.tar.gz
  sha256: b72b7607a2e1da76dff09d0ce7c05866cf56bdf66ea8ed4673c7520105ea1c6e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jql --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  homepage: https://github.com/yamafaktory/jql
  repository: https://github.com/yamafaktory/jql

extra:
  recipe-maintainers:
    - danielnachun
