context:
  version: "8.3.0"

package:
  name: jql
  version: ${{ version }}

source:
  url: https://github.com/yamafaktory/jql/archive/refs/tags/jql-v${{ version }}.tar.gz
  sha256: f336ff28fde0bf587fb6fdbdc5e2a5531bcc5b6618c80e5de12008452b9fab8b

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jql --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JSON query language CLI tool
  homepage: https://github.com/yamafaktory/jql
  repository: https://github.com/yamafaktory/jql

extra:
  recipe-maintainers:
    - danielnachun
